n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
soma = int(n1+n2)
subtração = int(n1-n2)
multiplicação = int(n1*n2)
divisão = float(n1/n2)
print(f'A soma entre esses dois número é {soma}')
print(f'A subtração entre esses dois números é {subtração}')
print(f'A multiplicação entre esses dois números é {multiplicação}')
print(f'A divisão entre esses dois números é {divisão}')